#------------------------------------------------------------------------------#
# This makefile was generated by 'cbp2make' tool rev.147                       #
#------------------------------------------------------------------------------#


WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
WINDRES = windres

INC = 
CFLAGS = -Wall -fexceptions
RESINC = 
LIBDIR = 
LIB = 
LDFLAGS = 

INC_DEBUG = $(INC)
CFLAGS_DEBUG = $(CFLAGS) -g
RESINC_DEBUG = $(RESINC)
RCFLAGS_DEBUG = $(RCFLAGS)
LIBDIR_DEBUG = $(LIBDIR)
LIB_DEBUG = $(LIB)
LDFLAGS_DEBUG = $(LDFLAGS)
OBJDIR_DEBUG = obj/Debug
DEP_DEBUG = 
OUT_DEBUG = bin/Debug/CasaInteligente

INC_RELEASE = $(INC)
CFLAGS_RELEASE = $(CFLAGS) -O2
RESINC_RELEASE = $(RESINC)
RCFLAGS_RELEASE = $(RCFLAGS)
LIBDIR_RELEASE = $(LIBDIR)
LIB_RELEASE = $(LIB)
LDFLAGS_RELEASE = $(LDFLAGS) -s
OBJDIR_RELEASE = obj/Release_rasbain
DEP_RELEASE = 
OUT_RELEASE = bin/Release_rasbian/CasaInteligente

OBJ_DEBUG = $(OBJDIR_DEBUG)/CasaInteligente.o $(OBJDIR_DEBUG)/Main.o $(OBJDIR_DEBUG)/Sensores.o

OBJ_RELEASE = $(OBJDIR_RELEASE)/CasaInteligente.o $(OBJDIR_RELEASE)/Main.o $(OBJDIR_RELEASE)/Sensores.o

all: debug release

clean: clean_debug clean_release

before_debug: 
	test -d bin/Debug || mkdir -p bin/Debug
	test -d $(OBJDIR_DEBUG) || mkdir -p $(OBJDIR_DEBUG)

after_debug: 

debug: before_debug out_debug after_debug

out_debug: before_debug $(OBJ_DEBUG) $(DEP_DEBUG)
	$(LD) $(LIBDIR_DEBUG) -o $(OUT_DEBUG) $(OBJ_DEBUG)  $(LDFLAGS_DEBUG) $(LIB_DEBUG)

$(OBJDIR_DEBUG)/CasaInteligente.o: CasaInteligente.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c CasaInteligente.cpp -o $(OBJDIR_DEBUG)/CasaInteligente.o

$(OBJDIR_DEBUG)/Main.o: Main.cc
	$(CC) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Main.cc -o $(OBJDIR_DEBUG)/Main.o

$(OBJDIR_DEBUG)/Sensores.o: Sensores.cpp
	$(CXX) $(CFLAGS_DEBUG) $(INC_DEBUG) -c Sensores.cpp -o $(OBJDIR_DEBUG)/Sensores.o

clean_debug: 
	rm -f $(OBJ_DEBUG) $(OUT_DEBUG)
	rm -rf bin/Debug
	rm -rf $(OBJDIR_DEBUG)

before_release: 
	test -d bin/Release_rasbian || mkdir -p bin/Release_rasbian
	test -d $(OBJDIR_RELEASE) || mkdir -p $(OBJDIR_RELEASE)

after_release: 

release: before_release out_release after_release

out_release: before_release $(OBJ_RELEASE) $(DEP_RELEASE)
	$(LD) $(LIBDIR_RELEASE) -o $(OUT_RELEASE) $(OBJ_RELEASE)  $(LDFLAGS_RELEASE) $(LIB_RELEASE)

$(OBJDIR_RELEASE)/CasaInteligente.o: CasaInteligente.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c CasaInteligente.cpp -o $(OBJDIR_RELEASE)/CasaInteligente.o

$(OBJDIR_RELEASE)/Main.o: Main.cc
	$(CC) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Main.cc -o $(OBJDIR_RELEASE)/Main.o

$(OBJDIR_RELEASE)/Sensores.o: Sensores.cpp
	$(CXX) $(CFLAGS_RELEASE) $(INC_RELEASE) -c Sensores.cpp -o $(OBJDIR_RELEASE)/Sensores.o

clean_release: 
	rm -f $(OBJ_RELEASE) $(OUT_RELEASE)
	rm -rf bin/Release_rasbian
	rm -rf $(OBJDIR_RELEASE)

.PHONY: before_debug after_debug clean_debug before_release after_release clean_release

